packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@lezer/common': ^1.5.2
  '@lezer/lr': ^1.4.2
  '@storybook/react-vite': 10.6.0
  '@tanstack/react-virtual': ^3.14.10
  'class-variance-authority': ^0.7.1
  'clsx': ^2.1.1
  'lucide-react': ^0.488.0
  'sonner': ^2.0.8
  'tailwind-merge': ^3.6.0
  'ts-pattern': ^5.9.0
  'vite': ^8.2.2
  'unplugin-dts': ^1.1.0
  'vitest': ^4.1.11
